import type { AdmissionPolicyDefinition } from "./contracts.js";
import { assertAdmissionPolicyDefinition } from "./policy.js";

const policies: readonly AdmissionPolicyDefinition[] = [
  {
    sourceKey: "FEODO_TRACKER",
    policyVersion: "feodo-tracker-admission-v1",
    admissionStatus: "ADMITTED",
    valueQuestion: "Which botnet command-and-control endpoints are published by Feodo Tracker in its non-aggressive IOC dataset?",
    officialAccessReference: "https://feodotracker.abuse.ch/blocklist/",
    termsReference: "https://feodotracker.abuse.ch/blocklist/",
    termsCheckedAt: "2026-08-13T21:20:00.000Z",
    reviewDueAt: "2027-02-13T00:00:00.000Z",
    licenseClass: "CC0-1.0",
    commercialUseStatus: "ALLOWED",
    redistributionStatus: "ALLOWED",
    rawRetentionStatus: "ALLOWED",
    canonicalRetentionStatus: "ALLOWED",
    derivedDataStatus: "ALLOWED",
    publicDisplayStatus: "ALLOWED",
    attributionRequirement: "CC0 does not require attribution; BAYKUSH retains the Feodo Tracker source reference and must not imply abuse.ch endorsement.",
    collectionAllowed: true,
    canonicalProjectionAllowed: true,
    measurementProjectionAllowed: true,
    operatorConstraints: "Use only the non-aggressive Feodo Tracker Botnet C2 IOC JSON dataset. Do not interpret report counts as attacks, victims, infections, bot population, attribution, or global threat level.",
    reviewedAt: "2026-08-13T21:20:00.000Z",
  },
  {
    sourceKey: "SSLBL_CERTIFICATE",
    policyVersion: "sslbl-certificate-admission-v1",
    admissionStatus: "ADMITTED",
    valueQuestion: "Which SHA1 certificate fingerprints does SSLBL publish as associated with malicious or botnet command-and-control activity?",
    officialAccessReference: "https://sslbl.abuse.ch/blacklist/",
    termsReference: "https://sslbl.abuse.ch/blacklist/",
    termsCheckedAt: "2026-08-13T21:40:00.000Z",
    reviewDueAt: "2027-02-13T00:00:00.000Z",
    licenseClass: "CC0-1.0",
    commercialUseStatus: "ALLOWED",
    redistributionStatus: "ALLOWED",
    rawRetentionStatus: "ALLOWED",
    canonicalRetentionStatus: "ALLOWED",
    derivedDataStatus: "ALLOWED",
    publicDisplayStatus: "ALLOWED",
    attributionRequirement: "CC0 does not require attribution; BAYKUSH retains the SSLBL source reference and must not imply abuse.ch endorsement.",
    collectionAllowed: true,
    canonicalProjectionAllowed: true,
    measurementProjectionAllowed: true,
    operatorConstraints: "Use the official malicious SSL certificate SHA1 blacklist. Do not interpret certificate listings as attacks, victims, infections, TLS prevalence, attribution, or global threat level. The deprecated SSLBL C2 IP CSV is not admitted as a production source.",
    reviewedAt: "2026-08-13T21:40:00.000Z",
  },
  {
    sourceKey: "GITHUB_ADVISORY_REVIEWED",
    policyVersion: "github-reviewed-advisory-admission-v1",
    admissionStatus: "ADMITTED",
    valueQuestion: "Which reviewed package-ecosystem security advisories are published through the GitHub Advisory Database?",
    officialAccessReference: "https://docs.github.com/en/rest/security-advisories/global-advisories",
    termsReference: "https://github.com/github/advisory-database/blob/main/LICENSE.md",
    termsCheckedAt: "2026-08-13T22:10:00.000Z",
    reviewDueAt: "2027-02-13T00:00:00.000Z",
    licenseClass: "CC-BY-4.0",
    commercialUseStatus: "ALLOWED",
    redistributionStatus: "ALLOWED",
    rawRetentionStatus: "ALLOWED",
    canonicalRetentionStatus: "ALLOWED",
    derivedDataStatus: "ALLOWED",
    publicDisplayStatus: "ALLOWED",
    attributionRequirement: "Preserve attribution to the GitHub Advisory Database and CC-BY-4.0 when sharing licensed or adapted material.",
    collectionAllowed: true,
    canonicalProjectionAllowed: true,
    measurementProjectionAllowed: true,
    operatorConstraints: "Collect only type=reviewed advisories. Do not admit unreviewed advisories as independent evidence because GitHub documents them as automatically published from NVD. Exclude malware advisories from this source contract.",
    reviewedAt: "2026-08-13T22:10:00.000Z",
  },
];

for (const policy of policies) assertAdmissionPolicyDefinition(policy);
export const admissionPolicyRegistry = new Map<string, AdmissionPolicyDefinition>(policies.map((policy) => [policy.sourceKey, policy]));
export const registeredAdmissionPolicies = Object.freeze([...admissionPolicyRegistry.values()]);
