import type { AdmissionPolicyDefinition } from "./contracts.js";
import { assertAdmissionPolicyDefinition } from "./policy.js";

const policies: readonly AdmissionPolicyDefinition[] = [
  {
    sourceKey: "FEODO_TRACKER",
    policyVersion: "feodo-tracker-admission-v1",
    admissionStatus: "ADMITTED",
    valueQuestion: "Which botnet command-and-control endpoints are published by Feodo Tracker in its non-aggressive IOC dataset?",
    officialAccessReference: "https://feodotracker.abuse.ch/blocklist/",
    termsReference: "https://feodotracker.abuse.ch/blocklist/",
    termsCheckedAt: "2026-08-13T21:20:00.000Z",
    reviewDueAt: "2027-02-13T00:00:00.000Z",
    licenseClass: "CC0-1.0",
    commercialUseStatus: "ALLOWED",
    redistributionStatus: "ALLOWED",
    rawRetentionStatus: "ALLOWED",
    canonicalRetentionStatus: "ALLOWED",
    derivedDataStatus: "ALLOWED",
    publicDisplayStatus: "ALLOWED",
    attributionRequirement: "CC0 does not require attribution; BAYKUSH retains the Feodo Tracker source reference and must not imply abuse.ch endorsement.",
    collectionAllowed: true,
    canonicalProjectionAllowed: true,
    measurementProjectionAllowed: true,
    operatorConstraints: "Use only the non-aggressive Feodo Tracker Botnet C2 IOC JSON dataset. Do not interpret report counts as attacks, victims, infections, bot population, attribution, or global threat level.",
    reviewedAt: "2026-08-13T21:20:00.000Z",
  },
  {
    sourceKey: "SSLBL_CERTIFICATE",
    policyVersion: "sslbl-certificate-admission-v1",
    admissionStatus: "ADMITTED",
    valueQuestion: "Which SHA1 certificate fingerprints does SSLBL publish as associated with malicious or botnet command-and-control activity?",
    officialAccessReference: "https://sslbl.abuse.ch/blacklist/",
    termsReference: "https://sslbl.abuse.ch/blacklist/",
    termsCheckedAt: "2026-08-13T21:40:00.000Z",
    reviewDueAt: "2027-02-13T00:00:00.000Z",
    licenseClass: "CC0-1.0",
    commercialUseStatus: "ALLOWED",
    redistributionStatus: "ALLOWED",
    rawRetentionStatus: "ALLOWED",
    canonicalRetentionStatus: "ALLOWED",
    derivedDataStatus: "ALLOWED",
    publicDisplayStatus: "ALLOWED",
    attributionRequirement: "CC0 does not require attribution; BAYKUSH retains the SSLBL source reference and must not imply abuse.ch endorsement.",
    collectionAllowed: true,
    canonicalProjectionAllowed: true,
    measurementProjectionAllowed: true,
    operatorConstraints: "Use the official malicious SSL certificate SHA1 blacklist. Do not interpret certificate listings as attacks, victims, infections, TLS prevalence, attribution, or global threat level. The deprecated SSLBL C2 IP CSV is not admitted as a production source.",
    reviewedAt: "2026-08-13T21:40:00.000Z",
  },
  {
    sourceKey: "GITHUB_ADVISORY_REVIEWED",
    policyVersion: "github-reviewed-advisory-admission-v1",
    admissionStatus: "ADMITTED",
    valueQuestion: "Which reviewed package-ecosystem security advisories are published through the GitHub Advisory Database?",
    officialAccessReference: "https://docs.github.com/en/rest/security-advisories/global-advisories",
    termsReference: "https://github.com/github/advisory-database/blob/main/LICENSE.md",
    termsCheckedAt: "2026-08-13T22:10:00.000Z",
    reviewDueAt: "2027-02-13T00:00:00.000Z",
    licenseClass: "CC-BY-4.0",
    commercialUseStatus: "ALLOWED",
    redistributionStatus: "ALLOWED",
    rawRetentionStatus: "ALLOWED",
    canonicalRetentionStatus: "ALLOWED",
    derivedDataStatus: "ALLOWED",
    publicDisplayStatus: "ALLOWED",
    attributionRequirement: "Preserve attribution to the GitHub Advisory Database and CC-BY-4.0 when sharing licensed or adapted material.",
    collectionAllowed: true,
    canonicalProjectionAllowed: true,
    measurementProjectionAllowed: true,
    operatorConstraints: "Collect only type=reviewed advisories. Do not admit unreviewed advisories as independent evidence because GitHub documents them as automatically published from NVD. Exclude malware advisories from this source contract.",
    reviewedAt: "2026-08-13T22:10:00.000Z",
  },
  {
    sourceKey: "MITRE_ATTACK_ENTERPRISE",
    policyVersion: "mitre-attack-enterprise-admission-v1",
    admissionStatus: "ADMITTED",
    valueQuestion: "What Enterprise techniques and sub-techniques are currently published in the official MITRE ATT&CK knowledge base?",
    officialAccessReference: "https://attack.mitre.org/resources/attack-data-and-tools/",
    termsReference: "https://attack.mitre.org/resources/terms-of-use/",
    termsCheckedAt: "2026-08-13T23:15:00.000Z",
    reviewDueAt: "2027-02-14T00:00:00.000Z",
    licenseClass: "MITRE_ATTACK_TERMS",
    commercialUseStatus: "ALLOWED",
    redistributionStatus: "RESTRICTED",
    rawRetentionStatus: "ALLOWED",
    canonicalRetentionStatus: "ALLOWED",
    derivedDataStatus: "ALLOWED",
    publicDisplayStatus: "RESTRICTED",
    attributionRequirement: "Reproduce MITRE's copyright designation and ATT&CK license when copying the data, preserve MITRE ATT&CK attribution, and do not imply MITRE endorsement.",
    collectionAllowed: true,
    canonicalProjectionAllowed: true,
    measurementProjectionAllowed: false,
    operatorConstraints: "Treat this source only as contextual technique knowledge. Do not project technique counts, snapshot changes, tactics, or version changes into cyber-activity measurements and do not infer campaign confirmation, attribution, prevalence, or threat level from ATT&CK publication state.",
    reviewedAt: "2026-08-13T23:15:00.000Z",
  },
  {
    sourceKey: "JVN_IPEDIA",
    policyVersion: "jvn-ipedia-admission-v1",
    admissionStatus: "ADMITTED",
    valueQuestion: "Which vulnerability countermeasure entries are newly published or updated through the official English JVN iPedia recent feeds?",
    officialAccessReference: "https://jvndb.jvn.jp/en/feed/",
    termsReference: "https://jvn.jp/en/rss/",
    termsCheckedAt: "2026-08-13T23:30:00.000Z",
    reviewDueAt: "2026-11-14T00:00:00.000Z",
    licenseClass: "JVN_FEED_TERMS",
    commercialUseStatus: "ALLOWED",
    redistributionStatus: "RESTRICTED",
    rawRetentionStatus: "ALLOWED",
    canonicalRetentionStatus: "ALLOWED",
    derivedDataStatus: "RESTRICTED",
    publicDisplayStatus: "RESTRICTED",
    attributionRequirement: "Retain JVN/JVN iPedia attribution and source links. Treat syndicated feed content as a snapshot of the publisher information at syndication time and direct users to JVN or the relevant vendor for the latest information.",
    collectionAllowed: true,
    canonicalProjectionAllowed: true,
    measurementProjectionAllowed: false,
    operatorConstraints: "Use only the official English JVN iPedia New and New/Updated JVNRSS feeds. This recent surface is not complete historical coverage, so do not project advisory counts into authoritative historical activity series until a separate coverage contract is admitted.",
    reviewedAt: "2026-08-13T23:30:00.000Z",
  },
];

for (const policy of policies) assertAdmissionPolicyDefinition(policy);
export const admissionPolicyRegistry = new Map<string, AdmissionPolicyDefinition>(policies.map((policy) => [policy.sourceKey, policy]));
export const registeredAdmissionPolicies = Object.freeze([...admissionPolicyRegistry.values()]);
