BEGIN;

ALTER TABLE stream_session_events
  DROP CONSTRAINT stream_session_events_event_type_check;

ALTER TABLE stream_session_events
  ADD CONSTRAINT stream_session_events_event_type_check CHECK (event_type IN (
    'CONNECTED','SUBSCRIBED','RRC_LIST_RECEIVED','RRC_LIST_CHANGED','PROVIDER_ERROR',
    'PROVIDER_DISCONNECT','BACKPRESSURE_LIMIT','DB_UNAVAILABLE','SCHEMA_REJECTION',
    'RECONNECT_SCHEDULED','DRAIN_REQUESTED','FORCED_TERMINATE','STREAM_TELEMETRY','CLOSED'
  ));

COMMIT;
