import { createHash } from "node:crypto";
import type { PoolClient } from "pg";
import { pool, withTransaction } from "../db/pool.js";
import type { SourceAdapter, ClassifiedFailure } from "../contracts/source.js";
import { canonicalJsonStringify, type PreparedRawRecord } from "../runtime/raw-record.js";
import { retryDelaySeconds } from "../runtime/retry.js";
import type { ClaimedBackfillSegment } from "./types.js";

interface SegmentRow { id:string;request_id:string;source_definition_id:string;source_key:string;segment_index:number;segment_kind:"INTERVAL"|"DATASET_DATE";window_start:Date|null;window_end:Date|null;dataset_date:Date|string|null;checkpoint:unknown; }
export async function claimBackfillSegment(workerId:string,leaseSeconds:number):Promise<ClaimedBackfillSegment|null>{return withTransaction(async client=>{const selected=await client.query<SegmentRow>(`SELECT segment.*,request.id AS request_id,source.source_key FROM historical_backfill_segments segment JOIN historical_backfill_requests request ON request.id=segment.request_id JOIN source_definitions source ON source.id=segment.source_definition_id WHERE request.status IN ('QUEUED','RUNNING') AND ((segment.state IN ('QUEUED','FAILED_RETRYABLE') AND segment.available_at<=now()) OR (segment.state='RUNNING' AND segment.lease_expires_at<now())) AND NOT EXISTS (SELECT 1 FROM collection_runs live WHERE live.source_definition_id=segment.source_definition_id AND live.purpose<>'HISTORICAL_BACKFILL' AND live.state IN ('QUEUED','RUNNING')) ORDER BY segment.created_at,segment.segment_index FOR UPDATE OF segment SKIP LOCKED LIMIT 1`);const row=selected.rows[0];if(!row)return null;const claimed=await client.query<{attempt_count:number}>(`UPDATE historical_backfill_segments SET state='RUNNING',attempt_count=attempt_count+1,lease_owner=$2,lease_expires_at=now()+($3::text||' seconds')::interval,started_at=COALESCE(started_at,now()),updated_at=now() WHERE id=$1 RETURNING attempt_count`,[row.id,workerId,leaseSeconds]);await client.query(`UPDATE historical_backfill_requests SET status='RUNNING',started_at=COALESCE(started_at,now()),updated_at=now() WHERE id=$1 AND status='QUEUED'`,[row.request_id]);return{id:row.id,requestId:row.request_id,sourceDefinitionId:row.source_definition_id,sourceKey:row.source_key,segmentIndex:row.segment_index,segmentKind:row.segment_kind,windowStart:row.window_start?.toISOString()??null,windowEnd:row.window_end?.toISOString()??null,datasetDate:row.dataset_date?String(row.dataset_date).slice(0,10):null,checkpoint:row.checkpoint,attemptCount:claimed.rows[0]?.attempt_count??1};});}

async function ensureRun(client:PoolClient,segment:ClaimedBackfillSegment){const key=`historical-backfill:${segment.id}`;const run=await client.query<{id:string}>(`INSERT INTO collection_runs(source_definition_id,trigger,purpose,state,idempotency_key,historical_backfill_segment_id,started_at) VALUES($1,'RECOVERY','HISTORICAL_BACKFILL','RUNNING',$2,$3,now()) ON CONFLICT(idempotency_key) DO UPDATE SET state='RUNNING',lease_owner=NULL,lease_expires_at=NULL,updated_at=now() RETURNING id`,[segment.sourceDefinitionId,key,segment.id]);const runId=run.rows[0]!.id;const work=await client.query<{id:string}>(`INSERT INTO collection_work_units(run_id,ordinal,work_key,descriptor,state,started_at) VALUES($1,0,$2,'{}','RUNNING',now()) ON CONFLICT(run_id,ordinal) DO UPDATE SET state='RUNNING',updated_at=now() RETURNING id`,[runId,createHash('sha256').update(segment.id).digest('hex')]);return{runId,workId:work.rows[0]!.id};}

export async function persistBackfillPage(input:{segment:ClaimedBackfillSegment;workerId:string;adapter:SourceAdapter;records:readonly PreparedRawRecord[];checkpoint:unknown;complete:boolean}){await withTransaction(async client=>{const lease=await client.query(`SELECT 1 FROM historical_backfill_segments WHERE id=$1 AND state='RUNNING' AND lease_owner=$2 FOR UPDATE`,[input.segment.id,input.workerId]);if(!lease.rowCount)throw new Error('Backfill lease lost before persistence');const ids=await ensureRun(client,input.segment);let inserted=0;for(const record of input.records){const raw=await client.query<{id:string}>(`INSERT INTO raw_source_records(source_definition_id,collection_run_id,collection_work_unit_id,source_record_id,payload_sha256,payload,published_at,effective_at,upstream_updated_at,source_url,adapter_version,source_schema_version) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7,$8,$9,$10,$11,$12) ON CONFLICT(source_definition_id,source_record_id,payload_sha256) DO NOTHING RETURNING id`,[input.segment.sourceDefinitionId,ids.runId,ids.workId,record.sourceRecordId,record.payloadSha256,record.payloadJson,record.publishedAt,record.effectiveAt,record.upstreamUpdatedAt,record.sourceUrl,input.adapter.definition.adapterVersion,record.sourceSchemaVersion]);if(raw.rows[0]){inserted++;await client.query(`INSERT INTO normalization_jobs(raw_record_id,source_definition_id,normalization_version,state) VALUES($1,$2,$3,'QUEUED') ON CONFLICT DO NOTHING`,[raw.rows[0].id,input.segment.sourceDefinitionId,input.adapter.normalizationVersion]);}}
await client.query(`UPDATE historical_backfill_segments SET state=$3,checkpoint=$4::jsonb,records_accepted=records_accepted+$5,records_inserted=records_inserted+$6,lease_owner=NULL,lease_expires_at=NULL,finished_at=CASE WHEN $3='SUCCEEDED' THEN now() ELSE NULL END,updated_at=now() WHERE id=$1 AND lease_owner=$2`,[input.segment.id,input.workerId,input.complete?'SUCCEEDED':'QUEUED',canonicalJsonStringify(input.checkpoint),input.records.length,inserted]);await client.query(`UPDATE collection_work_units SET state=$2,accepted_record_count=accepted_record_count+$3,inserted_record_count=inserted_record_count+$4,finished_at=CASE WHEN $2='SUCCEEDED' THEN now() ELSE NULL END,updated_at=now() WHERE id=$1`,[ids.workId,input.complete?'SUCCEEDED':'QUEUED',input.records.length,inserted]);await client.query(`UPDATE collection_runs SET state=$2,raw_records_accepted=raw_records_accepted+$3,raw_records_inserted=raw_records_inserted+$4,finished_at=CASE WHEN $2='SUCCEEDED' THEN now() ELSE NULL END,updated_at=now() WHERE id=$1`,[ids.runId,input.complete?'SUCCEEDED':'QUEUED',input.records.length,inserted]);if(input.complete)await finishRequest(client,input.segment.requestId);});}

async function finishRequest(client:PoolClient,requestId:string){const counts=await client.query<{total:number;complete:number;inserted:string}>(`SELECT count(*)::int total,count(*) FILTER(WHERE state='SUCCEEDED')::int complete,COALESCE(sum(records_inserted),0)::text inserted FROM historical_backfill_segments WHERE request_id=$1`,[requestId]);const row=counts.rows[0]!;await client.query(`UPDATE historical_backfill_requests SET segments_completed=$2::int,records_inserted=$3::bigint,status=CASE WHEN $2::int=$4::int THEN 'SUCCEEDED' ELSE 'RUNNING' END,finished_at=CASE WHEN $2::int=$4::int THEN now() ELSE NULL END,updated_at=now() WHERE id=$1`,[requestId,row.complete,row.inserted,row.total]);}

export async function failBackfillSegment(segment:ClaimedBackfillSegment,workerId:string,failure:ClassifiedFailure,maxAttempts:number){const retry=failure.retryable&&segment.attemptCount<maxAttempts;const delay=retry?retryDelaySeconds({attemptCount:segment.attemptCount,baseSeconds:5,maxSeconds:300,...(failure.retryAfterSeconds===undefined?{}:{providerRetryAfterSeconds:failure.retryAfterSeconds})}):0;await pool.query(`UPDATE historical_backfill_segments SET state=$3,available_at=CASE WHEN $3='FAILED_RETRYABLE' THEN now()+($6::int*interval '1 second') ELSE available_at END,lease_owner=NULL,lease_expires_at=NULL,failure_code=$4,failure_message=$5,finished_at=CASE WHEN $3='FAILED_TERMINAL' THEN now() ELSE NULL END,updated_at=now() WHERE id=$1 AND lease_owner=$2`,[segment.id,workerId,retry?'FAILED_RETRYABLE':'FAILED_TERMINAL',failure.code,failure.message,delay]);if(!retry)await pool.query(`UPDATE historical_backfill_requests SET status='FAILED',failure_code=$2,failure_message=$3,finished_at=now(),updated_at=now() WHERE id=$1`,[segment.requestId,failure.code,failure.message]);}
