import { config } from "../config.js";
import { CollectionFailure, classifyUnknownFailure } from "../runtime/failure.js";
import { prepareRawRecord } from "../runtime/raw-record.js";
import { adapterRegistry } from "../sources/registry.js";
import { firstEpssHistoricalWorkDescriptor } from "../sources/first-epss.js";
import { nvdHistoricalWorkDescriptor } from "../sources/nvd-cve.js";
import { claimBackfillSegment,failBackfillSegment,persistBackfillPage } from "./repository.js";

function descriptor(segment:Awaited<ReturnType<typeof claimBackfillSegment>>){if(!segment)throw new Error('segment required');if(segment.sourceKey==='NVD_CVE'&&segment.windowStart&&segment.windowEnd)return nvdHistoricalWorkDescriptor(segment.windowStart,segment.windowEnd,segment.checkpoint);if(segment.sourceKey==='FIRST_EPSS'&&segment.datasetDate)return firstEpssHistoricalWorkDescriptor(segment.datasetDate);throw new CollectionFailure('SCHEMA_ERROR',`Historical provider execution is unsupported for ${segment.sourceKey}`,false);}

export async function backfillTick(workerId=config.instanceId):Promise<boolean>{const segment=await claimBackfillSegment(workerId,config.workerLeaseSeconds);if(!segment)return false;const adapter=adapterRegistry.get(segment.sourceKey);if(!adapter){await failBackfillSegment(segment,workerId,{code:'INTERNAL_ERROR',retryable:false,message:'Historical adapter unavailable'},config.workerMaxAttempts);return true;}const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),Math.max(1000,(config.workerLeaseSeconds-5)*1000));try{const result=await adapter.fetch({work:adapter.workDescriptorSchema.parse(descriptor(segment)),signal:controller.signal});const next=result.nextWork===null?{}:result.nextWork;const rawBound=Math.min(adapter.maxRawRecordBytes??config.maxRawRecordBytes,config.globalMaxRawRecordBytes);const records=result.records.map(record=>{const times=adapter.extractTimes(record);return prepareRawRecord({sourceRecordId:adapter.identifyRawRecord(record),payload:adapter.rawPayload(record),publishedAt:times.publishedAt,effectiveAt:times.effectiveAt,upstreamUpdatedAt:times.upstreamUpdatedAt,sourceUrl:adapter.sourceReference(record),sourceSchemaVersion:adapter.sourceSchemaVersion(record)},rawBound);});await persistBackfillPage({segment,workerId,adapter,records,checkpoint:next,complete:result.complete});}catch(error){const failure=controller.signal.aborted?{code:'TIMEOUT' as const,retryable:true,message:'Backfill work exceeded its lease-safe timeout'}:error instanceof CollectionFailure?classifyUnknownFailure(error):adapter.classifyFailure(error);await failBackfillSegment(segment,workerId,failure,config.workerMaxAttempts);}finally{clearTimeout(timer);}return true;}
