import { describe,expect,it } from "vitest";
import { decoderRecordToRoutingObservation, definitiveOriginAsns, mrtDecoderRecordSchema } from "../src/recovery/contracts.js";
import { isAutomaticRecoveryReason, isRetryableRecoveryFailure, recoveryBackoffSeconds } from "../src/recovery/policy.js";
import { RecoveryProjectionAccumulator, recoveryCompleteness, summarizeAcquisitionBasis } from "../src/recovery/projection.js";

const base={schemaVersion:"NODE6_2_MRT_DECODER_V1" as const,recordIndex:7,recordType:"BGP4MP" as const,recordSubtype:"BGP4MP_UPDATE",sourceObservedAt:"2026-08-15T12:21:12.000Z",peerIp:"192.0.2.1",peerAsn:64500,announcedPrefixes:["192.0.2.0/24","198.51.100.0/24","2001:db8::/32"],withdrawnPrefixes:["203.0.113.0/24","2001:db8:1::/48"],asPathSegments:[{kind:"AS_SEQUENCE" as const,asns:[64496,64500]}]};

describe("NODE-6.2 MRT recovery semantics",()=>{
  it("counts one physical UPDATE separately from prefix events",()=>{const record=mrtDecoderRecordSchema.parse(base);const observation=decoderRecordToRoutingObservation({record,rrc:"rrc00",artifactSha256:"a".repeat(64),nodeReceivedAt:"2026-08-17T00:00:00Z"});const accumulator=new RecoveryProjectionAccumulator({rrc:"rrc00",artifactWindowStart:"2026-08-15T12:20:00Z",artifactWindowEnd:"2026-08-15T12:25:00Z",targetFrom:"2026-08-15T12:21:00Z",targetTo:"2026-08-15T12:22:00Z"});accumulator.accept(observation);const delta=accumulator.finalize()[0]?.delta;expect(delta?.updateMessages).toBe(1);expect(delta?.announcementPrefixEvents).toBe(3);expect(delta?.withdrawalPrefixEvents).toBe(2);expect(delta?.ipv4PrefixEvents).toBe(3);expect(delta?.ipv6PrefixEvents).toBe(2);});
  it("emits a trustworthy zero minute when a successfully decoded RRC has no updates",()=>{const accumulator=new RecoveryProjectionAccumulator({rrc:"rrc00",artifactWindowStart:"2026-08-15T12:20:00Z",artifactWindowEnd:"2026-08-15T12:25:00Z",targetFrom:"2026-08-15T12:22:00Z",targetTo:"2026-08-15T12:23:00Z"});const delta=accumulator.finalize()[0]?.delta;expect(delta?.updateMessages).toBe(0);expect(delta?.rrcs).toEqual(["rrc00"]);});
  it("never invents a definitive origin from an AS_SET",()=>{expect(definitiveOriginAsns([{kind:"AS_SET",asns:[64500,64501]}])).toEqual([]);expect(definitiveOriginAsns([{kind:"AS_SEQUENCE",asns:[64496,64500]}])).toEqual([64500]);});
  it("requires the entire frozen RRC population for complete recovery",()=>{expect(recoveryCompleteness(["rrc00","rrc01","rrc03"],["rrc00","rrc01"]).status).toBe("PARTIAL");expect(recoveryCompleteness(["rrc00","rrc01","rrc03"],["rrc00","rrc01","rrc03"]).status).toBe("COMPLETE");expect(recoveryCompleteness(["rrc00"],["rrc00"],1).status).toBe("DEGRADED");});
  it("keeps mixed live/recovery provenance explicit",()=>{expect(summarizeAcquisitionBasis(["LIVE_STREAM"])).toBe("LIVE_STREAM");expect(summarizeAcquisitionBasis(["MRT_RECOVERY"])).toBe("MRT_RECOVERY");expect(summarizeAcquisitionBasis(["LIVE_STREAM","MRT_RECOVERY"])).toBe("MIXED");});
  it("uses conservative auto-recovery and bounded retry policy",()=>{expect(isAutomaticRecoveryReason("PROVIDER_DISCONNECT")).toBe(true);expect(isAutomaticRecoveryReason("SOURCE_DISABLED")).toBe(false);expect(isRetryableRecoveryFailure("HTTP_SERVER_ERROR")).toBe(true);expect(isRetryableRecoveryFailure("DECODER_CORRUPT_RECORD")).toBe(false);expect(recoveryBackoffSeconds(1)).toBe(30);expect(recoveryBackoffSeconds(3)).toBe(120);});
});
