import type { MeasurementRegistration } from "./contracts.js";

const publicBase = {
  contractVersion: "v1" as const,
  zeroPolicy: "ZERO_REQUIRES_VALID_COVERAGE" as const,
  visibility: "PUBLIC" as const,
};

export const measurementRegistrations: readonly MeasurementRegistration[] = [
  {
    definition: {
      ...publicBase,
      measurementKey: "vulnerability.cisa_kev.additions",
      domain: "VULNERABILITY",
      displayLabel: "CISA KEV additions",
      description: "CVE identities whose CISA KEV source dateAdded falls on the measured day.",
      unit: "CVES",
      valueKind: "COUNT",
      primaryTimeAxis: "SOURCE_DATASET_DATE",
      timePrecision: "DATE",
      sourceKeys: ["CISA_KEV"],
      recordKinds: ["KNOWN_EXPLOITED_VULNERABILITY"],
      supportedGranularities: ["DAY"],
      supportedDimensions: [],
      coveragePolicy: "SOURCE_TIME_AVAILABILITY_REQUIRED",
      acquisitionPolicy: "SOURCE_TIME_RECONCILABLE",
      comparisonPolicy: { kind: "SUM_EVENTS", requireCompleteCoverage: true, requireSamePopulationProfile: false, requireSameSourceModelVersion: false },
      populationProfile: null,
      changeFeedPolicy: "FACT",
      represents: "CVE catalogue memberships whose CISA KEV dateAdded is the measured calendar date within the available KEV evidence population.",
      doesNotRepresent: "Exploit-event count, attack count, victim count, exploitation frequency, business risk, remediation priority, or global threat level.",
    },
    calculation: { calculationVersion: "v1", projectorKey: "CISA_KEV_V1", aggregationKind: "COUNT_DISTINCT", metadata: { identity: "CVE" } },
  },
  {
    definition: {
      ...publicBase,
      measurementKey: "vulnerability.cisa_kev.updates_observed",
      domain: "VULNERABILITY",
      displayLabel: "CISA KEV updates observed",
      description: "Immutable KEV source-record revisions observed by BAYKUSH after the first retained source revision.",
      unit: "RECORD_REVISIONS",
      valueKind: "COUNT",
      primaryTimeAxis: "NODE_RECEIVED_TIME",
      timePrecision: "INSTANT",
      sourceKeys: ["CISA_KEV"],
      recordKinds: ["KNOWN_EXPLOITED_VULNERABILITY"],
      supportedGranularities: ["HOUR", "DAY"],
      supportedDimensions: [],
      coveragePolicy: "SOURCE_COVERAGE_REQUIRED",
      acquisitionPolicy: "OBSERVATION_TIME_LIVE_ONLY",
      comparisonPolicy: { kind: "SUM_EVENTS", requireCompleteCoverage: true, requireSamePopulationProfile: false, requireSameSourceModelVersion: false },
      populationProfile: null,
      changeFeedPolicy: "BUCKET_SUMMARY",
      represents: "Source-record revisions BAYKUSH observed for existing CISA KEV CVE identities while live collection was valid.",
      doesNotRepresent: "Every edit performed by CISA, exact upstream edit time, exploit events, attack volume, victims, or threat escalation.",
    },
    calculation: { calculationVersion: "v1", projectorKey: "CISA_KEV_V1", aggregationKind: "COUNT_EVENTS", metadata: {} },
  },
  {
    definition: {
      ...publicBase,
      measurementKey: "vulnerability.cisa_kev.membership_removals_observed",
      domain: "VULNERABILITY",
      displayLabel: "CISA KEV removals observed",
      description: "CVE memberships absent from a later retained KEV catalogue manifest after being present in the prior manifest.",
      unit: "CVES",
      valueKind: "COUNT",
      primaryTimeAxis: "NODE_RECEIVED_TIME",
      timePrecision: "INSTANT",
      sourceKeys: ["CISA_KEV"],
      recordKinds: [],
      supportedGranularities: ["HOUR", "DAY"],
      supportedDimensions: [],
      coveragePolicy: "SNAPSHOT_CONFIRMATION_REQUIRED",
      acquisitionPolicy: "OBSERVATION_TIME_LIVE_ONLY",
      comparisonPolicy: { kind: "SUM_EVENTS", requireCompleteCoverage: true, requireSamePopulationProfile: false, requireSameSourceModelVersion: false },
      populationProfile: null,
      changeFeedPolicy: "FACT",
      represents: "Membership removals observed between consecutive retained CISA KEV catalogue manifests.",
      doesNotRepresent: "The exact time CISA removed a record, exploitation cessation, vulnerability remediation, attack decline, or victim count.",
    },
    calculation: { calculationVersion: "v1", projectorKey: "CISA_KEV_V1", aggregationKind: "COUNT_EVENTS", metadata: {} },
  },
  {
    definition: {
      ...publicBase,
      measurementKey: "vulnerability.cisa_kev.catalog_size",
      domain: "VULNERABILITY",
      displayLabel: "CISA KEV catalogue size",
      description: "Latest confirmed CISA KEV catalogue membership count for a covered interval.",
      unit: "CATALOG_MEMBERS",
      valueKind: "GAUGE",
      primaryTimeAxis: "NODE_RECEIVED_TIME",
      timePrecision: "INSTANT",
      sourceKeys: ["CISA_KEV"],
      recordKinds: [],
      supportedGranularities: ["HOUR", "DAY"],
      supportedDimensions: [],
      coveragePolicy: "SNAPSHOT_CONFIRMATION_REQUIRED",
      acquisitionPolicy: "SNAPSHOT_STATE",
      comparisonPolicy: { kind: "LAST_VALUE", requireCompleteCoverage: true, requireSamePopulationProfile: false, requireSameSourceModelVersion: false },
      populationProfile: null,
      changeFeedPolicy: "BUCKET_SUMMARY",
      represents: "The most recently confirmed number of memberships in CISA KEV under valid snapshot coverage.",
      doesNotRepresent: "Attack volume, exploitation prevalence, affected organizations, severity, or global threat level.",
    },
    calculation: { calculationVersion: "v1", projectorKey: "CISA_KEV_V1", aggregationKind: "SNAPSHOT_LAST_CARRY_FORWARD", metadata: {} },
  },
  {
    definition: {
      ...publicBase,
      measurementKey: "vulnerability.nvd.publications",
      domain: "VULNERABILITY",
      displayLabel: "NVD CVE publications",
      description: "Distinct CVE records placed on the NVD source-published time axis.",
      unit: "CVES",
      valueKind: "COUNT",
      primaryTimeAxis: "SOURCE_PUBLISHED_TIME",
      timePrecision: "INSTANT",
      sourceKeys: ["NVD_CVE"],
      recordKinds: ["VULNERABILITY_RECORD"],
      supportedGranularities: ["HOUR", "DAY"],
      supportedDimensions: [
        { key: "NVD_VULN_STATUS", topN: 20, includeOther: true },
        { key: "NVD_CWE", topN: 20, includeOther: true },
        { key: "NVD_CVSS_VERSION", topN: 10, includeOther: true },
      ],
      coveragePolicy: "SOURCE_TIME_AVAILABILITY_REQUIRED",
      acquisitionPolicy: "SOURCE_TIME_RECONCILABLE",
      comparisonPolicy: { kind: "SUM_EVENTS", requireCompleteCoverage: true, requireSamePopulationProfile: false, requireSameSourceModelVersion: false },
      populationProfile: null,
      changeFeedPolicy: "BUCKET_SUMMARY",
      represents: "Distinct retained NVD CVE records whose source-published timestamp falls within the interval.",
      doesNotRepresent: "Observed exploitation, attacks, victims, exploit probability, business risk, remediation priority, or independent corroboration of mirrored CISA fields.",
    },
    calculation: { calculationVersion: "v1", projectorKey: "NVD_CVE_V1", aggregationKind: "COUNT_DISTINCT", metadata: { identity: "CVE" } },
  },
  {
    definition: {
      ...publicBase,
      measurementKey: "vulnerability.nvd.modifications",
      domain: "VULNERABILITY",
      displayLabel: "NVD retained modifications",
      description: "Retained immutable NVD CVE source revisions on the source lastModified time axis.",
      unit: "RECORD_REVISIONS",
      valueKind: "COUNT",
      primaryTimeAxis: "UPSTREAM_UPDATED_TIME",
      timePrecision: "INSTANT",
      sourceKeys: ["NVD_CVE"],
      recordKinds: ["VULNERABILITY_RECORD"],
      supportedGranularities: ["HOUR", "DAY"],
      supportedDimensions: [],
      coveragePolicy: "SOURCE_TIME_AVAILABILITY_REQUIRED",
      acquisitionPolicy: "SOURCE_TIME_RECONCILABLE",
      comparisonPolicy: { kind: "SUM_EVENTS", requireCompleteCoverage: true, requireSamePopulationProfile: false, requireSameSourceModelVersion: false },
      populationProfile: null,
      changeFeedPolicy: "BUCKET_SUMMARY",
      represents: "Distinct retained NVD CVE source revisions identified by CVE and source lastModified time.",
      doesNotRepresent: "Every NVD edit operation, observed exploitation, attacks, victims, risk, severity movement, or threat escalation.",
    },
    calculation: { calculationVersion: "v1", projectorKey: "NVD_CVE_V1", aggregationKind: "COUNT_EVENTS", metadata: {} },
  },
  {
    definition: {
      ...publicBase,
      measurementKey: "exploitation.epss.scored_records",
      domain: "EXPLOITATION_CONTEXT",
      displayLabel: "EPSS retained scored records",
      description: "Retained daily EPSS score population under the BAYKUSH EPSS_HIGH_SIGNAL_V1 capture contract.",
      unit: "SCORE_ROWS",
      valueKind: "GAUGE",
      primaryTimeAxis: "SOURCE_DATASET_DATE",
      timePrecision: "DATE",
      sourceKeys: ["FIRST_EPSS"],
      recordKinds: ["EXPLOIT_PROBABILITY_SCORE"],
      supportedGranularities: ["DAY"],
      supportedDimensions: [],
      coveragePolicy: "DATASET_AVAILABILITY_REQUIRED",
      acquisitionPolicy: "DATASET_SNAPSHOT",
      comparisonPolicy: { kind: "LAST_VALUE", requireCompleteCoverage: true, requireSamePopulationProfile: true, requireSameSourceModelVersion: true },
      populationProfile: { key: "EPSS_HIGH_SIGNAL_V1", minimumEpss: 0.1, maximumRecords: 2500 },
      changeFeedPolicy: "NONE",
      represents: "The number of EPSS score rows retained by BAYKUSH for the source dataset date under EPSS_HIGH_SIGNAL_V1.",
      doesNotRepresent: "The full global EPSS population, exploitation events, attacks, victims, severity, business risk, remediation priority, or threat level.",
    },
    calculation: { calculationVersion: "v1", projectorKey: "FIRST_EPSS_V1", aggregationKind: "DATASET_COUNT", metadata: {} },
  },
  {
    definition: {
      ...publicBase,
      measurementKey: "exploitation.epss.score_distribution",
      domain: "EXPLOITATION_CONTEXT",
      displayLabel: "EPSS score distribution",
      description: "Score-band composition inside the retained EPSS_HIGH_SIGNAL_V1 daily population.",
      unit: "SCORE_ROWS",
      valueKind: "DISTRIBUTION",
      primaryTimeAxis: "SOURCE_DATASET_DATE",
      timePrecision: "DATE",
      sourceKeys: ["FIRST_EPSS"],
      recordKinds: ["EXPLOIT_PROBABILITY_SCORE"],
      supportedGranularities: ["DAY"],
      supportedDimensions: [{ key: "EPSS_SCORE_BAND", topN: null, includeOther: false }],
      coveragePolicy: "DATASET_AVAILABILITY_REQUIRED",
      acquisitionPolicy: "DATASET_SNAPSHOT",
      comparisonPolicy: { kind: "NONE", requireCompleteCoverage: true, requireSamePopulationProfile: true, requireSameSourceModelVersion: true },
      populationProfile: { key: "EPSS_HIGH_SIGNAL_V1", minimumEpss: 0.1, maximumRecords: 2500 },
      changeFeedPolicy: "NONE",
      represents: "The EPSS score-band composition of the explicitly bounded BAYKUSH EPSS_HIGH_SIGNAL_V1 retained population for a source dataset date.",
      doesNotRepresent: "A global EPSS distribution, exploitation-event distribution, attack volume, observed exploitation, severity, risk, or threat level.",
    },
    calculation: { calculationVersion: "v1", projectorKey: "FIRST_EPSS_V1", aggregationKind: "DISTRIBUTION_COUNT", metadata: {} },
  },
  {
    definition: {
      ...publicBase,
      measurementKey: "ioc.threatfox.reporting_volume",
      domain: "IOC_REPORTING",
      displayLabel: "ThreatFox IOC reporting volume",
      description: "Distinct ThreatFox provider report identities placed on the source first_seen time axis.",
      unit: "REPORTS",
      valueKind: "COUNT",
      primaryTimeAxis: "SOURCE_EFFECTIVE_TIME",
      timePrecision: "INSTANT",
      sourceKeys: ["THREATFOX"],
      recordKinds: ["IOC_REPORT"],
      supportedGranularities: ["FIVE_MINUTES", "HOUR", "DAY"],
      supportedDimensions: [
        { key: "IOC_TYPE", topN: 20, includeOther: true },
        { key: "THREATFOX_MALWARE_LABEL", topN: 20, includeOther: true },
      ],
      coveragePolicy: "SOURCE_TIME_AVAILABILITY_REQUIRED",
      acquisitionPolicy: "SOURCE_TIME_RECONCILABLE",
      comparisonPolicy: { kind: "SUM_EVENTS", requireCompleteCoverage: true, requireSamePopulationProfile: false, requireSameSourceModelVersion: false },
      populationProfile: null,
      changeFeedPolicy: "BUCKET_SUMMARY",
      represents: "Distinct IOC reports exposed by ThreatFox with source first_seen inside the measured interval.",
      doesNotRepresent: "Attack count, victim count, infection count, independent corroboration, current maliciousness, attacker origin, campaign attribution, or global threat level.",
    },
    calculation: { calculationVersion: "v1", projectorKey: "THREATFOX_V1", aggregationKind: "COUNT_EVENTS", metadata: {} },
  },
  {
    definition: {
      ...publicBase,
      measurementKey: "ioc.threatfox.distinct_indicators",
      domain: "IOC_REPORTING",
      displayLabel: "ThreatFox distinct normalized indicators",
      description: "Exact distinct normalized IOC entity identities within the requested interval.",
      unit: "INDICATORS",
      valueKind: "COUNT",
      primaryTimeAxis: "SOURCE_EFFECTIVE_TIME",
      timePrecision: "INSTANT",
      sourceKeys: ["THREATFOX"],
      recordKinds: ["IOC_REPORT"],
      supportedGranularities: ["FIVE_MINUTES", "HOUR", "DAY"],
      supportedDimensions: [{ key: "IOC_TYPE", topN: 20, includeOther: true }],
      coveragePolicy: "SOURCE_TIME_AVAILABILITY_REQUIRED",
      acquisitionPolicy: "SOURCE_TIME_RECONCILABLE",
      comparisonPolicy: { kind: "EXACT_DISTINCT_QUERY", requireCompleteCoverage: true, requireSamePopulationProfile: false, requireSameSourceModelVersion: false },
      populationProfile: null,
      changeFeedPolicy: "NONE",
      represents: "Distinct deterministic normalized indicator entity keys carried by ThreatFox reports in the interval.",
      doesNotRepresent: "Distinct attacks, victims, infrastructure owners, current malicious endpoints, independent corroboration, or global threat level. Unmapped source values are excluded from this normalized-identity metric.",
    },
    calculation: { calculationVersion: "v1", projectorKey: "THREATFOX_V1", aggregationKind: "COUNT_DISTINCT", metadata: { identity: "INDICATOR" } },
  },
  {
    definition: {
      ...publicBase,
      measurementKey: "ioc.threatfox.first_seen_indicators",
      domain: "IOC_REPORTING",
      displayLabel: "ThreatFox first-seen-by-Node indicators",
      description: "Normalized indicator identities whose current BAYKUSH entity history begins in the interval with ThreatFox as the first source.",
      unit: "INDICATORS",
      valueKind: "COUNT",
      primaryTimeAxis: "SOURCE_EFFECTIVE_TIME",
      timePrecision: "INSTANT",
      sourceKeys: ["THREATFOX"],
      recordKinds: ["IOC_REPORT"],
      supportedGranularities: ["FIVE_MINUTES", "HOUR", "DAY"],
      supportedDimensions: [{ key: "IOC_TYPE", topN: 20, includeOther: true }],
      coveragePolicy: "SOURCE_TIME_AVAILABILITY_REQUIRED",
      acquisitionPolicy: "SOURCE_TIME_RECONCILABLE",
      comparisonPolicy: { kind: "EXACT_DISTINCT_QUERY", requireCompleteCoverage: true, requireSamePopulationProfile: false, requireSameSourceModelVersion: false },
      populationProfile: null,
      changeFeedPolicy: "BUCKET_SUMMARY",
      represents: "Indicator identities first known to the BAYKUSH Node dataset in the interval under the current deterministic identity model, with ThreatFox as the first supporting source.",
      doesNotRepresent: "The first global existence of an IOC, first attacker use, first compromise, attack count, victim count, or independent corroboration.",
    },
    calculation: { calculationVersion: "v1", projectorKey: "THREATFOX_V1", aggregationKind: "FIRST_SEEN_DISTINCT", metadata: { identity: "INDICATOR" } },
  },
  {
    definition: {
      ...publicBase,
      measurementKey: "ioc.threatfox.report_updates_observed",
      domain: "IOC_REPORTING",
      displayLabel: "ThreatFox report updates observed",
      description: "New immutable source-record revisions observed for an existing ThreatFox report identity.",
      unit: "RECORD_REVISIONS",
      valueKind: "COUNT",
      primaryTimeAxis: "NODE_RECEIVED_TIME",
      timePrecision: "INSTANT",
      sourceKeys: ["THREATFOX"],
      recordKinds: ["IOC_REPORT"],
      supportedGranularities: ["HOUR", "DAY"],
      supportedDimensions: [],
      coveragePolicy: "SOURCE_COVERAGE_REQUIRED",
      acquisitionPolicy: "OBSERVATION_TIME_LIVE_ONLY",
      comparisonPolicy: { kind: "SUM_EVENTS", requireCompleteCoverage: true, requireSamePopulationProfile: false, requireSameSourceModelVersion: false },
      populationProfile: null,
      changeFeedPolicy: "BUCKET_SUMMARY",
      represents: "ThreatFox source-report payload revisions observed by BAYKUSH after the first retained report revision under live collection.",
      doesNotRepresent: "New attacks, new victims, a new campaign event, current maliciousness, or exact provider edit count.",
    },
    calculation: { calculationVersion: "v1", projectorKey: "THREATFOX_V1", aggregationKind: "COUNT_EVENTS", metadata: {} },
  },
  {
    definition: {
      ...publicBase,
      measurementKey: "malware.malwarebazaar.sample_reporting",
      domain: "MALWARE_REPORTING",
      displayLabel: "MalwareBazaar sample reporting",
      description: "Distinct repository sample SHA-256 identities on the MalwareBazaar source first_seen time axis.",
      unit: "SAMPLES",
      valueKind: "COUNT",
      primaryTimeAxis: "SOURCE_EFFECTIVE_TIME",
      timePrecision: "INSTANT",
      sourceKeys: ["MALWAREBAZAAR"],
      recordKinds: ["MALWARE_SAMPLE_RECORD"],
      supportedGranularities: ["FIVE_MINUTES", "HOUR", "DAY"],
      supportedDimensions: [
        { key: "MALWAREBAZAAR_FILE_TYPE", topN: 20, includeOther: true },
        { key: "MALWAREBAZAAR_SIGNATURE", topN: 20, includeOther: true },
      ],
      coveragePolicy: "SOURCE_TIME_AVAILABILITY_REQUIRED",
      acquisitionPolicy: "SOURCE_TIME_RECONCILABLE",
      comparisonPolicy: { kind: "SUM_EVENTS", requireCompleteCoverage: true, requireSamePopulationProfile: false, requireSameSourceModelVersion: false },
      populationProfile: null,
      changeFeedPolicy: "BUCKET_SUMMARY",
      represents: "Distinct MalwareBazaar repository sample identities whose source first_seen falls in the interval.",
      doesNotRepresent: "Malware infections, victim count, attack count, active campaign prevalence, attacker origin, target geography, independent corroboration, or global threat level.",
    },
    calculation: { calculationVersion: "v1", projectorKey: "MALWAREBAZAAR_V1", aggregationKind: "COUNT_EVENTS", metadata: {} },
  },
  {
    definition: {
      ...publicBase,
      measurementKey: "malware.malwarebazaar.distinct_hashes",
      domain: "MALWARE_REPORTING",
      displayLabel: "MalwareBazaar distinct SHA-256 hashes",
      description: "Exact distinct SHA-256 sample entity identities inside the requested interval.",
      unit: "HASHES",
      valueKind: "COUNT",
      primaryTimeAxis: "SOURCE_EFFECTIVE_TIME",
      timePrecision: "INSTANT",
      sourceKeys: ["MALWAREBAZAAR"],
      recordKinds: ["MALWARE_SAMPLE_RECORD"],
      supportedGranularities: ["FIVE_MINUTES", "HOUR", "DAY"],
      supportedDimensions: [],
      coveragePolicy: "SOURCE_TIME_AVAILABILITY_REQUIRED",
      acquisitionPolicy: "SOURCE_TIME_RECONCILABLE",
      comparisonPolicy: { kind: "EXACT_DISTINCT_QUERY", requireCompleteCoverage: true, requireSamePopulationProfile: false, requireSameSourceModelVersion: false },
      populationProfile: null,
      changeFeedPolicy: "NONE",
      represents: "Distinct normalized SHA-256 sample identities exposed by MalwareBazaar in the interval.",
      doesNotRepresent: "Distinct infections, victims, attacks, campaigns, current active malware instances, or threat level.",
    },
    calculation: { calculationVersion: "v1", projectorKey: "MALWAREBAZAAR_V1", aggregationKind: "COUNT_DISTINCT", metadata: { identity: "SHA256" } },
  },
  {
    definition: {
      ...publicBase,
      measurementKey: "malware.malwarebazaar.first_seen_hashes",
      domain: "MALWARE_REPORTING",
      displayLabel: "MalwareBazaar first-seen-by-Node hashes",
      description: "SHA-256 identities whose current BAYKUSH entity history begins in the interval with MalwareBazaar as first source.",
      unit: "HASHES",
      valueKind: "COUNT",
      primaryTimeAxis: "SOURCE_EFFECTIVE_TIME",
      timePrecision: "INSTANT",
      sourceKeys: ["MALWAREBAZAAR"],
      recordKinds: ["MALWARE_SAMPLE_RECORD"],
      supportedGranularities: ["FIVE_MINUTES", "HOUR", "DAY"],
      supportedDimensions: [],
      coveragePolicy: "SOURCE_TIME_AVAILABILITY_REQUIRED",
      acquisitionPolicy: "SOURCE_TIME_RECONCILABLE",
      comparisonPolicy: { kind: "EXACT_DISTINCT_QUERY", requireCompleteCoverage: true, requireSamePopulationProfile: false, requireSameSourceModelVersion: false },
      populationProfile: null,
      changeFeedPolicy: "BUCKET_SUMMARY",
      represents: "SHA-256 identities first known to the BAYKUSH Node dataset in the interval under the current identity model, with MalwareBazaar as the first supporting source.",
      doesNotRepresent: "The first creation or global appearance of the malware, first infection, attack count, victim count, prevalence, or campaign activity.",
    },
    calculation: { calculationVersion: "v1", projectorKey: "MALWAREBAZAAR_V1", aggregationKind: "FIRST_SEEN_DISTINCT", metadata: { identity: "SHA256" } },
  },
  {
    definition: {
      ...publicBase,
      measurementKey: "malware.malwarebazaar.sample_updates_observed",
      domain: "MALWARE_REPORTING",
      displayLabel: "MalwareBazaar sample updates observed",
      description: "New immutable repository metadata revisions observed for existing SHA-256 source identities.",
      unit: "RECORD_REVISIONS",
      valueKind: "COUNT",
      primaryTimeAxis: "NODE_RECEIVED_TIME",
      timePrecision: "INSTANT",
      sourceKeys: ["MALWAREBAZAAR"],
      recordKinds: ["MALWARE_SAMPLE_RECORD"],
      supportedGranularities: ["HOUR", "DAY"],
      supportedDimensions: [],
      coveragePolicy: "SOURCE_COVERAGE_REQUIRED",
      acquisitionPolicy: "OBSERVATION_TIME_LIVE_ONLY",
      comparisonPolicy: { kind: "SUM_EVENTS", requireCompleteCoverage: true, requireSamePopulationProfile: false, requireSameSourceModelVersion: false },
      populationProfile: null,
      changeFeedPolicy: "BUCKET_SUMMARY",
      represents: "MalwareBazaar sample metadata revisions observed by BAYKUSH for an already-retained SHA-256 identity under live collection.",
      doesNotRepresent: "A new infection, new victim, new attack, malware execution, campaign activity, or exact upstream edit count.",
    },
    calculation: { calculationVersion: "v1", projectorKey: "MALWAREBAZAAR_V1", aggregationKind: "COUNT_EVENTS", metadata: {} },
  },
  {
    definition: {
      measurementKey: "internal.synthetic.events",
      contractVersion: "v1",
      domain: "INTERNAL_TEST",
      displayLabel: "Synthetic measurement events",
      description: "Internal deterministic events used only for NODE-3 acceptance.",
      unit: "EVENTS",
      valueKind: "COUNT",
      primaryTimeAxis: "SOURCE_EFFECTIVE_TIME",
      timePrecision: "INSTANT",
      sourceKeys: ["TEST_SYNTHETIC"],
      recordKinds: ["UNKNOWN"],
      supportedGranularities: ["FIVE_MINUTES", "HOUR", "DAY"],
      supportedDimensions: [],
      coveragePolicy: "SOURCE_TIME_AVAILABILITY_REQUIRED",
      zeroPolicy: "ZERO_REQUIRES_VALID_COVERAGE",
      acquisitionPolicy: "SOURCE_TIME_RECONCILABLE",
      comparisonPolicy: { kind: "SUM_EVENTS", requireCompleteCoverage: true, requireSamePopulationProfile: false, requireSameSourceModelVersion: false },
      populationProfile: null,
      changeFeedPolicy: "NONE",
      visibility: "INTERNAL",
      represents: "Deterministic test events generated by the BAYKUSH synthetic source.",
      doesNotRepresent: "Any external cyber activity, threat, attack, victim, source observation, malware prevalence, or intelligence judgement.",
    },
    calculation: { calculationVersion: "v1", projectorKey: "TEST_SYNTHETIC_V1", aggregationKind: "COUNT_EVENTS", metadata: {} },
  },
] as const;
