import type { MeasurementRegistration } from "./contracts.js";

const publicBase = {
  contractVersion: "v1" as const,
  zeroPolicy: "ZERO_REQUIRES_VALID_COVERAGE" as const,
  visibility: "PUBLIC" as const,
};

const completeLiveComparison = {
  kind: "SUM_EVENTS" as const,
  requireCompleteCoverage: true,
  requireSamePopulationProfile: false,
  requireSameSourceModelVersion: false,
};

export const node5MeasurementRegistrations: readonly MeasurementRegistration[] = [
  {
    definition: {
      ...publicBase,
      measurementKey: "ioc.feodo_tracker.new_records_observed",
      domain: "IOC_REPORTING",
      displayLabel: "Feodo Tracker new C2 records observed",
      description: "First retained Feodo Tracker C2 source identities observed by BAYKUSH during valid live collection.",
      unit: "IOC_RECORDS",
      valueKind: "COUNT",
      primaryTimeAxis: "NODE_RECEIVED_TIME",
      timePrecision: "INSTANT",
      sourceKeys: ["FEODO_TRACKER"],
      recordKinds: ["IOC_REPORT"],
      supportedGranularities: ["HOUR", "DAY"],
      supportedDimensions: [
        { key: "FEODO_MALWARE_LABEL", topN: 20, includeOther: true },
        { key: "FEODO_COUNTRY", topN: 20, includeOther: true },
      ],
      coveragePolicy: "SOURCE_COVERAGE_REQUIRED",
      acquisitionPolicy: "OBSERVATION_TIME_LIVE_ONLY",
      comparisonPolicy: completeLiveComparison,
      populationProfile: null,
      changeFeedPolicy: "BUCKET_SUMMARY",
      represents: "Previously unretained Feodo Tracker C2 source identities that BAYKUSH first observed while live scheduled collection was valid.",
      doesNotRepresent: "The exact time the endpoint first existed, complete historical Feodo membership, attacks, victims, infections, bot population, attribution, organization compromise, or global threat level.",
    },
    calculation: {
      calculationVersion: "v1",
      projectorKey: "FEODO_TRACKER_V1",
      aggregationKind: "COUNT_EVENTS",
      metadata: { identity: "FEODO_SOURCE_IDENTITY", liveFirstRevisionOnly: true },
    },
  },
  {
    definition: {
      ...publicBase,
      measurementKey: "ioc.sslbl.certificate_listings_observed",
      domain: "IOC_REPORTING",
      displayLabel: "SSLBL certificate listings observed",
      description: "Previously unretained SSLBL certificate identities first observed by BAYKUSH during valid live collection.",
      unit: "CERTIFICATES",
      valueKind: "COUNT",
      primaryTimeAxis: "NODE_RECEIVED_TIME",
      timePrecision: "INSTANT",
      sourceKeys: ["SSLBL_CERTIFICATE"],
      recordKinds: ["IOC_REPORT"],
      supportedGranularities: ["HOUR", "DAY"],
      supportedDimensions: [],
      coveragePolicy: "SOURCE_COVERAGE_REQUIRED",
      acquisitionPolicy: "OBSERVATION_TIME_LIVE_ONLY",
      comparisonPolicy: completeLiveComparison,
      populationProfile: null,
      changeFeedPolicy: "BUCKET_SUMMARY",
      represents: "Previously unretained SHA1 certificate listing identities that BAYKUSH first observed in SSLBL while live scheduled collection was valid.",
      doesNotRepresent: "Complete historical SSLBL listing activity, certificate compromise proof, global TLS activity, attacks, victims, infections, attribution, organization compromise, or global threat level.",
    },
    calculation: {
      calculationVersion: "v1",
      projectorKey: "SSLBL_CERTIFICATE_V1",
      aggregationKind: "COUNT_EVENTS",
      metadata: { identity: "CERTIFICATE_SHA1", liveFirstRevisionOnly: true },
    },
  },
  {
    definition: {
      ...publicBase,
      measurementKey: "vulnerability.github_advisory.publications",
      domain: "VULNERABILITY",
      displayLabel: "GitHub reviewed advisory publications",
      description: "Reviewed GitHub Advisory Database records placed on their source-published time axis.",
      unit: "ADVISORIES",
      valueKind: "COUNT",
      primaryTimeAxis: "SOURCE_PUBLISHED_TIME",
      timePrecision: "INSTANT",
      sourceKeys: ["GITHUB_ADVISORY_REVIEWED"],
      recordKinds: ["SECURITY_ADVISORY"],
      supportedGranularities: ["HOUR", "DAY"],
      supportedDimensions: [{ key: "GITHUB_ADVISORY_SEVERITY", topN: 10, includeOther: true }],
      coveragePolicy: "SOURCE_TIME_AVAILABILITY_REQUIRED",
      acquisitionPolicy: "SOURCE_TIME_RECONCILABLE",
      comparisonPolicy: completeLiveComparison,
      populationProfile: { advisoryType: "reviewed", excludes: ["unreviewed", "malware"] },
      changeFeedPolicy: "BUCKET_SUMMARY",
      represents: "Distinct retained GitHub-reviewed security-advisory identities whose source-published timestamp falls within the interval.",
      doesNotRepresent: "Unreviewed NVD-derived advisories, malware advisories, exploitation events, attack volume, package deployment prevalence, organization exposure, business risk, remediation priority, or global threat level.",
    },
    calculation: {
      calculationVersion: "v1",
      projectorKey: "GITHUB_ADVISORY_REVIEWED_V1",
      aggregationKind: "COUNT_EVENTS",
      metadata: { identity: "GHSA_ID" },
    },
  },
  {
    definition: {
      ...publicBase,
      measurementKey: "vulnerability.github_advisory.updates_observed",
      domain: "VULNERABILITY",
      displayLabel: "GitHub reviewed advisory updates observed",
      description: "Retained source-record revisions for reviewed GitHub advisories observed by BAYKUSH after the first revision.",
      unit: "RECORD_REVISIONS",
      valueKind: "COUNT",
      primaryTimeAxis: "NODE_RECEIVED_TIME",
      timePrecision: "INSTANT",
      sourceKeys: ["GITHUB_ADVISORY_REVIEWED"],
      recordKinds: ["SECURITY_ADVISORY"],
      supportedGranularities: ["HOUR", "DAY"],
      supportedDimensions: [{ key: "GITHUB_ADVISORY_SEVERITY", topN: 10, includeOther: true }],
      coveragePolicy: "SOURCE_COVERAGE_REQUIRED",
      acquisitionPolicy: "OBSERVATION_TIME_LIVE_ONLY",
      comparisonPolicy: completeLiveComparison,
      populationProfile: { advisoryType: "reviewed", excludes: ["unreviewed", "malware"] },
      changeFeedPolicy: "BUCKET_SUMMARY",
      represents: "Immutable source-record revisions BAYKUSH observed for already-retained GitHub-reviewed advisory identities during valid live collection.",
      doesNotRepresent: "Every upstream GitHub edit, exact upstream edit time, exploitation, attacks, affected installations, organization exposure, business risk, or threat escalation.",
    },
    calculation: {
      calculationVersion: "v1",
      projectorKey: "GITHUB_ADVISORY_REVIEWED_V1",
      aggregationKind: "COUNT_EVENTS",
      metadata: { liveRevisionsOnly: true },
    },
  },
  {
    definition: {
      ...publicBase,
      measurementKey: "vulnerability.cisa_ics.advisory_publications",
      domain: "VULNERABILITY",
      displayLabel: "CISA ICS advisory publications",
      description: "CISA-distributed OT CSAF advisories placed on their source initial-release time axis.",
      unit: "ADVISORIES",
      valueKind: "COUNT",
      primaryTimeAxis: "SOURCE_PUBLISHED_TIME",
      timePrecision: "INSTANT",
      sourceKeys: ["CISA_ICS_CSAF"],
      recordKinds: ["SECURITY_ADVISORY"],
      supportedGranularities: ["HOUR", "DAY"],
      supportedDimensions: [{ key: "CISA_ICS_PUBLISHER", topN: 20, includeOther: true }],
      coveragePolicy: "SOURCE_TIME_AVAILABILITY_REQUIRED",
      acquisitionPolicy: "SOURCE_TIME_RECONCILABLE",
      comparisonPolicy: completeLiveComparison,
      populationProfile: { repositorySurface: "OT_WHITE" },
      changeFeedPolicy: "BUCKET_SUMMARY",
      represents: "Distinct retained CISA-distributed OT CSAF advisory identities whose source initial-release timestamp falls within the interval.",
      doesNotRepresent: "Independent exploitation confirmation, attacks, victims, customer exposure, remediation priority, business risk, attribution truth, or global threat level.",
    },
    calculation: {
      calculationVersion: "v1",
      projectorKey: "CISA_ICS_CSAF_V1",
      aggregationKind: "COUNT_EVENTS",
      metadata: { identity: "CISA_ICS_ADVISORY_ID" },
    },
  },
  {
    definition: {
      ...publicBase,
      measurementKey: "vulnerability.cisa_ics.advisory_updates_observed",
      domain: "VULNERABILITY",
      displayLabel: "CISA ICS advisory updates observed",
      description: "Retained CISA ICS CSAF source-record revisions observed by BAYKUSH after the first revision.",
      unit: "RECORD_REVISIONS",
      valueKind: "COUNT",
      primaryTimeAxis: "NODE_RECEIVED_TIME",
      timePrecision: "INSTANT",
      sourceKeys: ["CISA_ICS_CSAF"],
      recordKinds: ["SECURITY_ADVISORY"],
      supportedGranularities: ["HOUR", "DAY"],
      supportedDimensions: [{ key: "CISA_ICS_PUBLISHER", topN: 20, includeOther: true }],
      coveragePolicy: "SOURCE_COVERAGE_REQUIRED",
      acquisitionPolicy: "OBSERVATION_TIME_LIVE_ONLY",
      comparisonPolicy: completeLiveComparison,
      populationProfile: { repositorySurface: "OT_WHITE" },
      changeFeedPolicy: "BUCKET_SUMMARY",
      represents: "Immutable CISA ICS CSAF source-record revisions BAYKUSH observed for already-retained advisory identities during valid live collection.",
      doesNotRepresent: "Every publisher edit, exact publisher edit time, exploitation, attack volume, victims, exposure, risk, remediation priority, or threat escalation.",
    },
    calculation: {
      calculationVersion: "v1",
      projectorKey: "CISA_ICS_CSAF_V1",
      aggregationKind: "COUNT_EVENTS",
      metadata: { liveRevisionsOnly: true },
    },
  },
];
