import { createHash } from "node:crypto";
import { createReadStream } from "node:fs";
import { spawn } from "node:child_process";
import { createInterface } from "node:readline";
import { once } from "node:events";
import { config } from "../config.js";
import { decoderRecordToRoutingObservation, mrtDecoderRecordSchema, type MrtDecoderRecord } from "./contracts.js";
import { DECODER_CONTRACT_VERSION, DECODER_NAME, DECODER_UPSTREAM_COMMIT, DECODER_UPSTREAM_TAG, DECODER_VERSION } from "./policy.js";
import { RecoveryFailure } from "./errors.js";
import type { RoutingObservation } from "../stream/contracts.js";

async function sha256File(file:string):Promise<string>{const hash=createHash("sha256");const stream=createReadStream(file);stream.on("data",(chunk:Buffer)=>hash.update(chunk));await once(stream,"end");return hash.digest("hex");}
export interface DecoderRunResult{decoderName:string;decoderVersion:string;decoderUpstreamTag:string;decoderUpstreamCommit:string;decoderBinarySha256:string;decoderContractVersion:string;arguments:string[];recordsRead:number;updatesDecoded:number;recordsIgnored:number;recordsRejected:number;outputSha256:string;exitCode:number;}

export async function runMrtDecoder(input:{artifactPath:string;artifactSha256:string;rrc:string;onObservation:(observation:RoutingObservation,record:MrtDecoderRecord)=>void|Promise<void>}):Promise<DecoderRunResult>{const binarySha=await sha256File(config.recoveryDecoderPath);const child=spawn(config.recoveryDecoderPath,[input.artifactPath],{shell:false,stdio:["ignore","pipe","pipe"],env:{PATH:process.env.PATH??"/usr/bin:/bin",LANG:"C.UTF-8",LC_ALL:"C.UTF-8"}});if(!child.stdout||!child.stderr)throw new RecoveryFailure("DECODER_EXIT_NONZERO","Decoder stdio unavailable");let timedOut=false;let stderr="";let outputBytes=0;let records=0;const outputHash=createHash("sha256");child.stderr.setEncoding("utf8");child.stderr.on("data",(chunk:string)=>{if(stderr.length<65536)stderr+=(chunk.slice(0,65536-stderr.length));});const timer=setTimeout(()=>{timedOut=true;child.kill("SIGKILL");},config.recoveryDecoderTimeoutMs);const exitPromise=new Promise<number>((resolve,reject)=>{child.once("error",reject);child.once("exit",(code)=>resolve(code??-1));});try{const lines=createInterface({input:child.stdout,crlfDelay:Infinity});for await(const line of lines){if(line.length===0)continue;outputBytes+=Buffer.byteLength(line)+1;if(outputBytes>config.recoveryDecoderMaxOutputBytes){child.kill("SIGKILL");throw new RecoveryFailure("DECODER_OUTPUT_LIMIT","Decoder output byte limit exceeded");}records+=1;if(records>config.recoveryDecoderMaxRecords){child.kill("SIGKILL");throw new RecoveryFailure("DECODER_OUTPUT_LIMIT","Decoder record limit exceeded");}outputHash.update(line);outputHash.update("\n");let record:MrtDecoderRecord;try{record=mrtDecoderRecordSchema.parse(JSON.parse(line));}catch(error){child.kill("SIGKILL");throw new RecoveryFailure("DECODER_OUTPUT_INVALID","Decoder emitted invalid NODE6_2_MRT_DECODER_V1 JSONL",error);}const observation=decoderRecordToRoutingObservation({record,rrc:input.rrc,artifactSha256:input.artifactSha256,nodeReceivedAt:new Date().toISOString()});await input.onObservation(observation,record);}const exitCode=await exitPromise;if(timedOut)throw new RecoveryFailure("DECODER_TIMEOUT","Pinned MRT decoder exceeded execution timeout");if(exitCode!==0)throw new RecoveryFailure("DECODER_EXIT_NONZERO",`Pinned MRT decoder exited ${exitCode}: ${stderr.trim().slice(0,2048)}`);return{decoderName:DECODER_NAME,decoderVersion:DECODER_VERSION,decoderUpstreamTag:DECODER_UPSTREAM_TAG,decoderUpstreamCommit:DECODER_UPSTREAM_COMMIT,decoderBinarySha256:binarySha,decoderContractVersion:DECODER_CONTRACT_VERSION,arguments:["<local-staged-artifact>"],recordsRead:records,updatesDecoded:records,recordsIgnored:0,recordsRejected:0,outputSha256:outputHash.digest("hex"),exitCode};}catch(error){if(!child.killed)child.kill("SIGKILL");await exitPromise.catch(()=>-1);if(error instanceof RecoveryFailure)throw error;throw new RecoveryFailure("DECODER_EXIT_NONZERO","Pinned MRT decoder execution failed",error);}finally{clearTimeout(timer);}}
