import { createHash } from "node:crypto";
import { pool,withTransaction } from "../db/pool.js";
export interface RipeMrtUpdateSegment{index:number;rrc:string;windowStart:string;windowEnd:string;url:string;}
function parse(value:string):number{const ms=Date.parse(value);if(!Number.isFinite(ms))throw new Error("Recovery time must be RFC3339");return ms;}
function assertRrc(rrc:string):string{const normalized=rrc.toLowerCase();if(!/^rrc\d{2}$/.test(normalized))throw new Error(`Invalid RIPE RRC: ${rrc}`);return normalized;}
function pad(value:number):string{return String(value).padStart(2,"0");}
function urlFor(rrc:string,start:Date):string{const year=start.getUTCFullYear();const month=pad(start.getUTCMonth()+1);const day=pad(start.getUTCDate());const hour=pad(start.getUTCHours());const minute=pad(start.getUTCMinutes());return`https://data.ris.ripe.net/${rrc}/${year}.${month}/update.${year}${month}${day}.${hour}${minute}.gz`;}
export function planRipeMrtUpdateSegments(input:{rrcs:readonly string[];from:string;to:string;maxSegments?:number}):RipeMrtUpdateSegment[]{const from=parse(input.from);const to=parse(input.to);if(to<=from)throw new Error("Recovery to must be after from");const rrcs=[...new Set(input.rrcs.map(assertRrc))].sort();if(rrcs.length===0)throw new Error("At least one RRC is required");const maxSegments=input.maxSegments??5000;if(!Number.isInteger(maxSegments)||maxSegments<1||maxSegments>10000)throw new Error("Invalid recovery segment bound");const interval=5*60*1000;let cursor=Math.floor(from/interval)*interval;const output:RipeMrtUpdateSegment[]=[];while(cursor<to){for(const rrc of rrcs){if(output.length>=maxSegments)throw new Error("Recovery plan exceeds segment bound");const start=new Date(cursor);output.push({index:output.length,rrc,windowStart:start.toISOString(),windowEnd:new Date(cursor+interval).toISOString(),url:urlFor(rrc,start)});}cursor+=interval;}return output;}
export async function persistRecoveryPlan(input:{from:string;to:string;rrcs:readonly string[];reason:string}):Promise<{requestId:string;segments:number}>{const source=await pool.query<{id:string}>(`SELECT id FROM source_definitions WHERE source_key='RIPE_RIS_BGP'`);const sourceId=source.rows[0]?.id;if(!sourceId)throw new Error("RIPE_RIS_BGP source definition is unavailable");const plan=planRipeMrtUpdateSegments({rrcs:input.rrcs,from:input.from,to:input.to});return withTransaction(async(client)=>{const request=await client.query<{id:string}>(`INSERT INTO stream_recovery_requests(source_definition_id,requested_from,requested_to,rrc_set,reason,status,segments_planned) VALUES($1,$2,$3,$4::jsonb,$5,'PLANNED',$6) RETURNING id`,[sourceId,input.from,input.to,JSON.stringify([...new Set(input.rrcs.map((v)=>v.toLowerCase()))].sort()),input.reason,plan.length]);const requestId=request.rows[0]?.id;if(!requestId)throw new Error("Failed to create recovery request");for(const segment of plan)await client.query(`INSERT INTO stream_recovery_segments(recovery_request_id,source_definition_id,segment_index,rrc,window_start,window_end,source_url) VALUES($1,$2,$3,$4,$5,$6,$7)`,[requestId,sourceId,segment.index,segment.rrc,segment.windowStart,segment.windowEnd,segment.url]);return{requestId,segments:plan.length};});}
export function recoveryPlanFingerprint(plan:readonly RipeMrtUpdateSegment[]):string{return createHash("sha256").update(JSON.stringify(plan)).digest("hex");}
