import { createHash } from "node:crypto";
import { canonicalJsonStringify } from "../../runtime/raw-record.js";
import { getMeasurementRegistration } from "../registry.js";
import type { AcquisitionBasis,CandidateEntityObservation,CandidateFact,CanonicalEntity,CanonicalProjectionInput } from "./types.js";
export function sha256(value:unknown):string{return createHash("sha256").update(canonicalJsonStringify(value)).digest("hex");}
export function factMap(input:unknown):Map<string,unknown>{const output=new Map<string,unknown>();if(!Array.isArray(input))return output;for(const item of input){if(!item||typeof item!=="object"||Array.isArray(item))continue;const object=item as Record<string,unknown>;if(typeof object.predicate==="string")output.set(object.predicate,object.value);}return output;}
export function canonicalEntities(input:unknown):CanonicalEntity[]{if(!Array.isArray(input))return[];const output:CanonicalEntity[]=[];for(const item of input){if(!item||typeof item!=="object"||Array.isArray(item))continue;const object=item as Record<string,unknown>;if(typeof object.kind!=="string"||typeof object.key!=="string")continue;output.push({kind:object.kind,key:object.key,...(typeof object.label==="string"?{label:object.label}:{})});}return output;}
export function stringFact(facts:Map<string,unknown>,predicate:string):string|null{const value=facts.get(predicate);return typeof value==="string"&&value.length>0?value:null;}
export function numberFact(facts:Map<string,unknown>,predicate:string):number|null{const value=facts.get(predicate);return typeof value==="number"&&Number.isFinite(value)?value:null;}
export function acquisitionBasis(trigger:string,purpose:string):AcquisitionBasis{if(purpose==="INITIAL_BOOTSTRAP"||trigger==="BOOTSTRAP")return"INITIAL_BOOTSTRAP";if(purpose==="HISTORICAL_BACKFILL")return"HISTORICAL_BACKFILL";if(purpose==="RESYNC")return"RESYNC";if(purpose==="REPAIR")return"REPAIR";if(trigger==="RECOVERY")return"RECOVERY";return"LIVE_INCREMENTAL";}
export function liveObservationAllowed(input:{trigger:string;purpose:string}):boolean{return input.trigger==="SCHEDULED"&&input.purpose==="LIVE_INCREMENTAL";}
export function makeCandidate(input:Omit<CandidateFact,"factKey"|"inputFingerprint">&{identity:unknown;fingerprintMaterial:unknown}):CandidateFact{if(!getMeasurementRegistration(input.measurementKey))throw new Error(`Unknown measurement ${input.measurementKey}`);const factKey=sha256({measurementKey:input.measurementKey,identity:input.identity});const inputFingerprint=sha256({measurementKey:input.measurementKey,factKey,factKind:input.factKind,eventTime:input.eventTime,eventDate:input.eventDate,timePrecision:input.timePrecision,numericValue:input.numericValue,entityKey:input.entityKey,entityType:input.entityType,dimensions:input.dimensions,acquisitionBasis:input.acquisitionBasis,sourceModelVersion:input.sourceModelVersion,source:input.fingerprintMaterial});return{measurementKey:input.measurementKey,factKey,factKind:input.factKind,eventTime:input.eventTime,eventDate:input.eventDate,timePrecision:input.timePrecision,numericValue:input.numericValue,entityKey:input.entityKey,entityType:input.entityType,dimensions:input.dimensions,acquisitionBasis:input.acquisitionBasis,sourceModelVersion:input.sourceModelVersion,inputFingerprint,inputRole:input.inputRole};}
export function objectPayload(input:unknown):Record<string,unknown>|null{return input&&typeof input==="object"&&!Array.isArray(input)?input as Record<string,unknown>:null;}
export function projectDefaultEntityObservations(input:CanonicalProjectionInput):CandidateEntityObservation[]{const facts=factMap(input.facts);let observedTime:string|null=input.effectiveAt??input.publishedAt??input.upstreamUpdatedAt??input.receivedAt;let observedDate:string|null=null;let timePrecision:"INSTANT"|"DATE"="INSTANT";if(input.sourceKey==="CISA_KEV"){const dateAdded=stringFact(facts,"kev.date_added");if(dateAdded){observedTime=null;observedDate=dateAdded;timePrecision="DATE";}}else if(input.sourceKey==="FIRST_EPSS"){const scoreDate=stringFact(facts,"epss.score_date");if(scoreDate){observedTime=null;observedDate=scoreDate;timePrecision="DATE";}}if(!observedTime&&!observedDate)return[];return canonicalEntities(input.entities).map((entity,index)=>{const entityRole=index===0?"PRIMARY":"RELATED";const identity={sourceKey:input.sourceKey,sourceRecordId:input.sourceRecordId,entityType:entity.kind,entityKey:entity.key,entityRole};return{observationKey:sha256(identity),entityKey:entity.key,entityType:entity.kind,entityRole,observedTime,observedDate,timePrecision,inputFingerprint:sha256({identity,observedTime,observedDate,normalizedSha256:input.normalizedSha256})};});}
