import os from "node:os";
import { z } from "zod";

const booleanFromEnv=z.preprocess((value)=>{if(typeof value!=="string")return value;if(["1","true","yes","on"].includes(value.toLowerCase()))return true;if(["0","false","no","off"].includes(value.toLowerCase()))return false;return value;},z.boolean());
const optionalSecretFromEnv=z.preprocess((value)=>typeof value==="string"&&value.trim()===""?undefined:value,z.string().min(1).max(4096).optional());
const absolutePath=z.string().min(1).max(4096).refine((value)=>value.startsWith("/"),"must be an absolute path");

const envSchema=z.object({
  DATABASE_URL:z.string().min(1),PORT:z.coerce.number().int().min(1).max(65535).default(8080),NODE_INSTANCE_ID:z.string().min(1).max(128).optional(),DATABASE_POOL_MAX:z.coerce.number().int().min(1).max(50).default(10),
  SCHEDULER_TICK_MS:z.coerce.number().int().min(250).max(60000).default(5000),WORKER_IDLE_MS:z.coerce.number().int().min(100).max(60000).default(1000),WORKER_LEASE_SECONDS:z.coerce.number().int().min(10).max(900).default(60),WORKER_MAX_ATTEMPTS:z.coerce.number().int().min(1).max(20).default(3),WORKER_RETRY_BASE_SECONDS:z.coerce.number().int().min(1).max(300).default(5),WORKER_RETRY_MAX_SECONDS:z.coerce.number().int().min(1).max(3600).default(300),
  NORMALIZER_IDLE_MS:z.coerce.number().int().min(100).max(60000).default(1000),NORMALIZER_LEASE_SECONDS:z.coerce.number().int().min(10).max(900).default(60),NORMALIZER_MAX_ATTEMPTS:z.coerce.number().int().min(1).max(20).default(3),HEARTBEAT_INTERVAL_MS:z.coerce.number().int().min(1000).max(60000).default(10000),
  SOURCE_HTTP_TIMEOUT_MS:z.coerce.number().int().min(1000).max(120000).default(30000),MAX_RECORDS_PER_WORK_UNIT:z.coerce.number().int().min(1).max(10000).default(100),GLOBAL_MAX_RECORDS_PER_WORK_UNIT:z.coerce.number().int().min(1).max(10000).default(10000),MAX_RAW_RECORD_BYTES:z.coerce.number().int().min(1024).max(64*1024*1024).default(262144),GLOBAL_MAX_RAW_RECORD_BYTES:z.coerce.number().int().min(1024).max(64*1024*1024).default(8*1024*1024),
  NVD_API_KEY:optionalSecretFromEnv,THREATFOX_AUTH_KEY:optionalSecretFromEnv,MALWAREBAZAAR_AUTH_KEY:optionalSecretFromEnv,ENABLE_TEST_SYNTHETIC:booleanFromEnv.default(false),SYNTHETIC_RECORDS_PER_RUN:z.coerce.number().int().min(1).max(10000).default(25),SYNTHETIC_PAGE_SIZE:z.coerce.number().int().min(1).max(1000).default(10),
  STREAM_IDLE_MS:z.coerce.number().int().min(250).max(60000).default(5000),STREAM_RECONNECT_BASE_MS:z.coerce.number().int().min(250).max(60000).default(1000),STREAM_RECONNECT_MAX_MS:z.coerce.number().int().min(1000).max(600000).default(60000),STREAM_QUEUE_MAX_MESSAGES:z.coerce.number().int().min(100).max(1000000).default(50000),STREAM_QUEUE_MAX_BYTES:z.coerce.number().int().min(1048576).max(1073741824).default(67108864),STREAM_SEGMENT_MAX_MESSAGES:z.coerce.number().int().min(10).max(100000).default(5000),STREAM_SEGMENT_MAX_BYTES:z.coerce.number().int().min(65536).max(67108864).default(4194304),STREAM_FLUSH_INTERVAL_MS:z.coerce.number().int().min(100).max(10000).default(1000),STREAM_MAX_MESSAGE_BYTES:z.coerce.number().int().min(1024).max(16777216).default(1048576),STREAM_RAW_RETENTION_HOURS:z.coerce.number().int().min(1).max(168).default(48),
  RECOVERY_AUTO_ENABLED:booleanFromEnv.default(false),RECOVERY_IDLE_MS:z.coerce.number().int().min(250).max(60000).default(1000),RECOVERY_LEASE_SECONDS:z.coerce.number().int().min(30).max(3600).default(300),RECOVERY_MAX_ATTEMPTS:z.coerce.number().int().min(1).max(20).default(4),RECOVERY_RETRY_BASE_SECONDS:z.coerce.number().int().min(1).max(3600).default(30),RECOVERY_RETRY_MAX_SECONDS:z.coerce.number().int().min(1).max(21600).default(1800),RECOVERY_ARCHIVE_SETTLE_SECONDS:z.coerce.number().int().min(0).max(86400).default(900),RECOVERY_MAX_SEGMENTS:z.coerce.number().int().min(1).max(10000).default(10000),
  RECOVERY_STAGING_DIR:absolutePath.default("/var/lib/baykush/recovery"),RECOVERY_DOWNLOAD_TIMEOUT_MS:z.coerce.number().int().min(1000).max(900000).default(120000),RECOVERY_MAX_ARTIFACT_BYTES:z.coerce.number().int().min(1024*1024).max(4*1024*1024*1024).default(512*1024*1024),RECOVERY_MIN_FREE_DISK_BYTES:z.coerce.number().int().min(0).max(1024*1024*1024*1024).default(1024*1024*1024),RECOVERY_ARTIFACT_RETENTION_HOURS:z.coerce.number().int().min(1).max(168).default(24),
  RECOVERY_DECODER_PATH:absolutePath.default("/usr/local/bin/baykush-mrt-decoder"),RECOVERY_DECODER_TIMEOUT_MS:z.coerce.number().int().min(1000).max(1800000).default(300000),RECOVERY_DECODER_MAX_OUTPUT_BYTES:z.coerce.number().int().min(1024*1024).max(4*1024*1024*1024).default(1024*1024*1024),RECOVERY_DECODER_MAX_RECORDS:z.coerce.number().int().min(1).max(50000000).default(10000000),RECOVERY_PAUSE_ON_STREAM_UNHEALTHY:booleanFromEnv.default(true),
});

const parsed=envSchema.parse(process.env);
if(parsed.MAX_RECORDS_PER_WORK_UNIT>parsed.GLOBAL_MAX_RECORDS_PER_WORK_UNIT)throw new Error("MAX_RECORDS_PER_WORK_UNIT cannot exceed GLOBAL_MAX_RECORDS_PER_WORK_UNIT");
if(parsed.MAX_RAW_RECORD_BYTES>parsed.GLOBAL_MAX_RAW_RECORD_BYTES)throw new Error("MAX_RAW_RECORD_BYTES cannot exceed GLOBAL_MAX_RAW_RECORD_BYTES");
if(parsed.SYNTHETIC_PAGE_SIZE>parsed.MAX_RECORDS_PER_WORK_UNIT)throw new Error("SYNTHETIC_PAGE_SIZE cannot exceed MAX_RECORDS_PER_WORK_UNIT");
if(parsed.WORKER_RETRY_BASE_SECONDS>parsed.WORKER_RETRY_MAX_SECONDS)throw new Error("WORKER_RETRY_BASE_SECONDS cannot exceed WORKER_RETRY_MAX_SECONDS");
if(parsed.STREAM_RECONNECT_BASE_MS>parsed.STREAM_RECONNECT_MAX_MS)throw new Error("STREAM_RECONNECT_BASE_MS cannot exceed STREAM_RECONNECT_MAX_MS");
if(parsed.STREAM_SEGMENT_MAX_MESSAGES>parsed.STREAM_QUEUE_MAX_MESSAGES)throw new Error("STREAM_SEGMENT_MAX_MESSAGES cannot exceed STREAM_QUEUE_MAX_MESSAGES");
if(parsed.STREAM_SEGMENT_MAX_BYTES>parsed.STREAM_QUEUE_MAX_BYTES)throw new Error("STREAM_SEGMENT_MAX_BYTES cannot exceed STREAM_QUEUE_MAX_BYTES");
if(parsed.RECOVERY_RETRY_BASE_SECONDS>parsed.RECOVERY_RETRY_MAX_SECONDS)throw new Error("RECOVERY_RETRY_BASE_SECONDS cannot exceed RECOVERY_RETRY_MAX_SECONDS");

export const config=Object.freeze({
  databaseUrl:parsed.DATABASE_URL,port:parsed.PORT,instanceId:parsed.NODE_INSTANCE_ID??`${os.hostname()}:${process.pid}`,databasePoolMax:parsed.DATABASE_POOL_MAX,schedulerTickMs:parsed.SCHEDULER_TICK_MS,workerIdleMs:parsed.WORKER_IDLE_MS,workerLeaseSeconds:parsed.WORKER_LEASE_SECONDS,workerMaxAttempts:parsed.WORKER_MAX_ATTEMPTS,workerRetryBaseSeconds:parsed.WORKER_RETRY_BASE_SECONDS,workerRetryMaxSeconds:parsed.WORKER_RETRY_MAX_SECONDS,normalizerIdleMs:parsed.NORMALIZER_IDLE_MS,normalizerLeaseSeconds:parsed.NORMALIZER_LEASE_SECONDS,normalizerMaxAttempts:parsed.NORMALIZER_MAX_ATTEMPTS,heartbeatIntervalMs:parsed.HEARTBEAT_INTERVAL_MS,sourceHttpTimeoutMs:parsed.SOURCE_HTTP_TIMEOUT_MS,maxRecordsPerWorkUnit:parsed.MAX_RECORDS_PER_WORK_UNIT,globalMaxRecordsPerWorkUnit:parsed.GLOBAL_MAX_RECORDS_PER_WORK_UNIT,maxRawRecordBytes:parsed.MAX_RAW_RECORD_BYTES,globalMaxRawRecordBytes:parsed.GLOBAL_MAX_RAW_RECORD_BYTES,nvdApiKey:parsed.NVD_API_KEY,threatFoxAuthKey:parsed.THREATFOX_AUTH_KEY,malwareBazaarAuthKey:parsed.MALWAREBAZAAR_AUTH_KEY,enableTestSynthetic:parsed.ENABLE_TEST_SYNTHETIC,syntheticRecordsPerRun:parsed.SYNTHETIC_RECORDS_PER_RUN,syntheticPageSize:parsed.SYNTHETIC_PAGE_SIZE,streamIdleMs:parsed.STREAM_IDLE_MS,streamReconnectBaseMs:parsed.STREAM_RECONNECT_BASE_MS,streamReconnectMaxMs:parsed.STREAM_RECONNECT_MAX_MS,streamQueueMaxMessages:parsed.STREAM_QUEUE_MAX_MESSAGES,streamQueueMaxBytes:parsed.STREAM_QUEUE_MAX_BYTES,streamSegmentMaxMessages:parsed.STREAM_SEGMENT_MAX_MESSAGES,streamSegmentMaxBytes:parsed.STREAM_SEGMENT_MAX_BYTES,streamFlushIntervalMs:parsed.STREAM_FLUSH_INTERVAL_MS,streamMaxMessageBytes:parsed.STREAM_MAX_MESSAGE_BYTES,streamRawRetentionHours:parsed.STREAM_RAW_RETENTION_HOURS,
  recoveryAutoEnabled:parsed.RECOVERY_AUTO_ENABLED,recoveryIdleMs:parsed.RECOVERY_IDLE_MS,recoveryLeaseSeconds:parsed.RECOVERY_LEASE_SECONDS,recoveryMaxAttempts:parsed.RECOVERY_MAX_ATTEMPTS,recoveryRetryBaseSeconds:parsed.RECOVERY_RETRY_BASE_SECONDS,recoveryRetryMaxSeconds:parsed.RECOVERY_RETRY_MAX_SECONDS,recoveryArchiveSettleSeconds:parsed.RECOVERY_ARCHIVE_SETTLE_SECONDS,recoveryMaxSegments:parsed.RECOVERY_MAX_SEGMENTS,recoveryStagingDir:parsed.RECOVERY_STAGING_DIR,recoveryDownloadTimeoutMs:parsed.RECOVERY_DOWNLOAD_TIMEOUT_MS,recoveryMaxArtifactBytes:parsed.RECOVERY_MAX_ARTIFACT_BYTES,recoveryMinFreeDiskBytes:parsed.RECOVERY_MIN_FREE_DISK_BYTES,recoveryArtifactRetentionHours:parsed.RECOVERY_ARTIFACT_RETENTION_HOURS,recoveryDecoderPath:parsed.RECOVERY_DECODER_PATH,recoveryDecoderTimeoutMs:parsed.RECOVERY_DECODER_TIMEOUT_MS,recoveryDecoderMaxOutputBytes:parsed.RECOVERY_DECODER_MAX_OUTPUT_BYTES,recoveryDecoderMaxRecords:parsed.RECOVERY_DECODER_MAX_RECORDS,recoveryPauseOnStreamUnhealthy:parsed.RECOVERY_PAUSE_ON_STREAM_UNHEALTHY,
});
